services:
  - type: web
    name: skill-specific-backend
    runtime: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        sync: false
